export interface ListingMetric {
  listing_id: string;
  store_id: 'metro' | 'windy';
  rakuten_item_no: string;
  rakuten_sku: string;
  title: string;
  stock_qty: number;
  last_month_sales: number;
  this_month_sales: number;
  r_hat: number; // 需要推定（日次）
  bom_qty: number; // このSKU1個あたりに必要な社内ID数
  contribution_stock: number; // 在庫への寄与（stock_qty * bom_qty）
  contribution_consumption: number; // 消費への寄与（r_hat * bom_qty）
}

export interface ItemMetric {
  internal_id: string;
  name: string;
  derived_stock: number;
  avg_daily_consumption: number;
  days_of_cover: number;
  lead_time_days: number;
  safety_stock: number;
  lot_size: number;
  target_cover_days: number;
  need_qty: number;
  reorder_qty_suggested: number;
  risk_level: 'red' | 'yellow' | 'green' | 'surplus';
  default_unit_cost?: number;
  listings?: ListingMetric[]; // 紐づくSKU一覧
}

export interface MirrorMismatch {
  internal_id: string;
  name: string;
  metro_stock_qty: number;
  windy_stock_qty: number;
  diff: number;
}

import type { POHeader, POLine } from './po-schema';

export const mockItemMetrics: ItemMetric[] = [
  {
    internal_id: 'ITM-000123',
    name: 'デッキブラシ替えスポンジ',
    derived_stock: 45,
    avg_daily_consumption: 3.2,
    days_of_cover: 14.1,
    lead_time_days: 14,
    safety_stock: 30,
    lot_size: 50,
    target_cover_days: 28,
    need_qty: 74.6,
    reorder_qty_suggested: 100,
    risk_level: 'red',
    default_unit_cost: 320,
    listings: [
      {
        listing_id: 'metro|12345|SKU-01',
        store_id: 'metro',
        rakuten_item_no: '12345',
        rakuten_sku: 'SKU-01',
        title: 'デッキブラシ替えスポンジ 単品',
        stock_qty: 25,
        last_month_sales: 68,
        this_month_sales: 45,
        r_hat: 2.1,
        bom_qty: 1,
        contribution_stock: 25,
        contribution_consumption: 2.1,
      },
      {
        listing_id: 'metro|12345|SKU-02',
        store_id: 'metro',
        rakuten_item_no: '12345',
        rakuten_sku: 'SKU-02',
        title: 'デッキブラシ替えスポンジ 2個セット',
        stock_qty: 10,
        last_month_sales: 22,
        this_month_sales: 18,
        r_hat: 0.55,
        bom_qty: 2,
        contribution_stock: 20,
        contribution_consumption: 1.1,
      },
    ],
  },
  {
    internal_id: 'ITM-000124',
    name: 'キッチンスポンジ 10個セット',
    derived_stock: 180,
    avg_daily_consumption: 5.8,
    days_of_cover: 31.0,
    lead_time_days: 10,
    safety_stock: 50,
    lot_size: 100,
    target_cover_days: 24,
    need_qty: 0,
    reorder_qty_suggested: 0,
    risk_level: 'green',
    default_unit_cost: 850,
    listings: [
      {
        listing_id: 'metro|23456|SKU-A1',
        store_id: 'metro',
        rakuten_item_no: '23456',
        rakuten_sku: 'SKU-A1',
        title: 'キッチンスポンジ 10個セット',
        stock_qty: 180,
        last_month_sales: 165,
        this_month_sales: 98,
        r_hat: 5.8,
        bom_qty: 1,
        contribution_stock: 180,
        contribution_consumption: 5.8,
      },
    ],
  },
  {
    internal_id: 'ITM-000125',
    name: 'マイクロファイバークロス',
    derived_stock: 95,
    avg_daily_consumption: 4.5,
    days_of_cover: 21.1,
    lead_time_days: 14,
    safety_stock: 40,
    lot_size: 50,
    target_cover_days: 28,
    need_qty: 31,
    reorder_qty_suggested: 50,
    risk_level: 'yellow',
    default_unit_cost: 180,
    listings: [
      {
        listing_id: 'metro|34567|SKU-B1',
        store_id: 'metro',
        rakuten_item_no: '34567',
        rakuten_sku: 'SKU-B1',
        title: 'マイクロファイバークロス 単品',
        stock_qty: 55,
        last_month_sales: 92,
        this_month_sales: 58,
        r_hat: 3.2,
        bom_qty: 1,
        contribution_stock: 55,
        contribution_consumption: 3.2,
      },
      {
        listing_id: 'metro|34567|SKU-B2',
        store_id: 'metro',
        rakuten_item_no: '34567',
        rakuten_sku: 'SKU-B2',
        title: 'マイクロファイバークロス 3枚セット',
        stock_qty: 20,
        last_month_sales: 28,
        this_month_sales: 15,
        r_hat: 0.65,
        bom_qty: 3,
        contribution_stock: 40,
        contribution_consumption: 1.3,
      },
    ],
  },
  {
    internal_id: 'ITM-000126',
    name: '食器用洗剤 詰め替え用',
    derived_stock: 220,
    avg_daily_consumption: 8.2,
    days_of_cover: 26.8,
    lead_time_days: 7,
    safety_stock: 60,
    lot_size: 100,
    target_cover_days: 21,
    need_qty: 12.2,
    reorder_qty_suggested: 100,
    risk_level: 'yellow',
    default_unit_cost: 240,
    listings: [
      {
        listing_id: 'metro|45678|SKU-C1',
        store_id: 'metro',
        rakuten_item_no: '45678',
        rakuten_sku: 'SKU-C1',
        title: '食器用洗剤 詰め替え用 500ml',
        stock_qty: 150,
        last_month_sales: 185,
        this_month_sales: 120,
        r_hat: 6.5,
        bom_qty: 1,
        contribution_stock: 150,
        contribution_consumption: 6.5,
      },
      {
        listing_id: 'metro|45678|SKU-C2',
        store_id: 'metro',
        rakuten_item_no: '45678',
        rakuten_sku: 'SKU-C2',
        title: '食器用洗剤 詰め替え用 2本セット',
        stock_qty: 35,
        last_month_sales: 32,
        this_month_sales: 18,
        r_hat: 0.85,
        bom_qty: 2,
        contribution_stock: 70,
        contribution_consumption: 1.7,
      },
    ],
  },
  {
    internal_id: 'ITM-000127',
    name: 'トイレクリーナー',
    derived_stock: 35,
    avg_daily_consumption: 2.8,
    days_of_cover: 12.5,
    lead_time_days: 10,
    safety_stock: 20,
    lot_size: 50,
    target_cover_days: 24,
    need_qty: 52.2,
    reorder_qty_suggested: 100,
    risk_level: 'red',
    default_unit_cost: 420,
    listings: [
      {
        listing_id: 'metro|56789|SKU-D1',
        store_id: 'metro',
        rakuten_item_no: '56789',
        rakuten_sku: 'SKU-D1',
        title: 'トイレクリーナー 単品',
        stock_qty: 35,
        last_month_sales: 78,
        this_month_sales: 52,
        r_hat: 2.8,
        bom_qty: 1,
        contribution_stock: 35,
        contribution_consumption: 2.8,
      },
    ],
  },
  {
    internal_id: 'ITM-000128',
    name: 'ガラスクリーナースプレー',
    derived_stock: 140,
    avg_daily_consumption: 3.5,
    days_of_cover: 40.0,
    lead_time_days: 12,
    safety_stock: 30,
    lot_size: 50,
    target_cover_days: 26,
    need_qty: 0,
    reorder_qty_suggested: 0,
    risk_level: 'green',
    default_unit_cost: 380,
    listings: [
      {
        listing_id: 'metro|67890|SKU-E1',
        store_id: 'metro',
        rakuten_item_no: '67890',
        rakuten_sku: 'SKU-E1',
        title: 'ガラスクリーナースプレー 500ml',
        stock_qty: 90,
        last_month_sales: 65,
        this_month_sales: 42,
        r_hat: 2.3,
        bom_qty: 1,
        contribution_stock: 90,
        contribution_consumption: 2.3,
      },
      {
        listing_id: 'metro|67890|SKU-E2',
        store_id: 'metro',
        rakuten_item_no: '67890',
        rakuten_sku: 'SKU-E2',
        title: 'ガラスクリーナースプレー 2本セット',
        stock_qty: 25,
        last_month_sales: 22,
        this_month_sales: 12,
        r_hat: 0.6,
        bom_qty: 2,
        contribution_stock: 50,
        contribution_consumption: 1.2,
      },
    ],
  },
  {
    internal_id: 'ITM-000129',
    name: 'フロアワイパーシート 30枚',
    derived_stock: 88,
    avg_daily_consumption: 4.1,
    days_of_cover: 21.5,
    lead_time_days: 14,
    safety_stock: 35,
    lot_size: 50,
    target_cover_days: 28,
    need_qty: 62,
    reorder_qty_suggested: 100,
    risk_level: 'yellow',
    default_unit_cost: 550,
    listings: [
      {
        listing_id: 'metro|78901|SKU-F1',
        store_id: 'metro',
        rakuten_item_no: '78901',
        rakuten_sku: 'SKU-F1',
        title: 'フロアワイパーシート 30枚入',
        stock_qty: 88,
        last_month_sales: 115,
        this_month_sales: 72,
        r_hat: 4.1,
        bom_qty: 1,
        contribution_stock: 88,
        contribution_consumption: 4.1,
      },
    ],
  },
  {
    internal_id: 'ITM-000130',
    name: 'ゴミ袋 45L 50枚入',
    derived_stock: 310,
    avg_daily_consumption: 6.5,
    days_of_cover: 47.7,
    lead_time_days: 7,
    safety_stock: 50,
    lot_size: 100,
    target_cover_days: 21,
    need_qty: 0,
    reorder_qty_suggested: 0,
    risk_level: 'green',
    default_unit_cost: 680,
    listings: [
      {
        listing_id: 'metro|89012|SKU-G1',
        store_id: 'metro',
        rakuten_item_no: '89012',
        rakuten_sku: 'SKU-G1',
        title: 'ゴミ袋 45L 50枚入',
        stock_qty: 210,
        last_month_sales: 145,
        this_month_sales: 95,
        r_hat: 5.2,
        bom_qty: 1,
        contribution_stock: 210,
        contribution_consumption: 5.2,
      },
      {
        listing_id: 'metro|89012|SKU-G2',
        store_id: 'metro',
        rakuten_item_no: '89012',
        rakuten_sku: 'SKU-G2',
        title: 'ゴミ袋 45L 50枚入 2袋セット',
        stock_qty: 50,
        last_month_sales: 25,
        this_month_sales: 15,
        r_hat: 0.65,
        bom_qty: 2,
        contribution_stock: 100,
        contribution_consumption: 1.3,
      },
    ],
  },
  {
    internal_id: 'ITM-000999',
    name: '在庫過多テスト品（ダミー）',
    derived_stock: 1200,
    avg_daily_consumption: 3.0,
    days_of_cover: 400.0,
    lead_time_days: 14,
    safety_stock: 0,
    lot_size: 1,
    target_cover_days: 28,
    need_qty: 0,
    reorder_qty_suggested: 0,
    risk_level: 'surplus',
    default_unit_cost: 100,
    listings: [
      {
        listing_id: 'metro|99999|SKU-Z1',
        store_id: 'metro',
        rakuten_item_no: '99999',
        rakuten_sku: 'SKU-Z1',
        title: '在庫過多テスト品（ダミー）',
        stock_qty: 1200,
        last_month_sales: 0,
        this_month_sales: 0,
        r_hat: 3.0,
        bom_qty: 1,
        contribution_stock: 1200,
        contribution_consumption: 3.0,
      },
    ],
  },
  {
    internal_id: 'ITM-000131',
    name: 'バスクリーナー 泡タイプ',
    derived_stock: 62,
    avg_daily_consumption: 2.9,
    days_of_cover: 21.4,
    lead_time_days: 10,
    safety_stock: 25,
    lot_size: 50,
    target_cover_days: 24,
    need_qty: 32.6,
    reorder_qty_suggested: 50,
    risk_level: 'yellow',
    default_unit_cost: 450,
    listings: [
      {
        listing_id: 'metro|90123|SKU-H1',
        store_id: 'metro',
        rakuten_item_no: '90123',
        rakuten_sku: 'SKU-H1',
        title: 'バスクリーナー 泡タイプ 400ml',
        stock_qty: 62,
        last_month_sales: 82,
        this_month_sales: 55,
        r_hat: 2.9,
        bom_qty: 1,
        contribution_stock: 62,
        contribution_consumption: 2.9,
      },
    ],
  },
  {
    internal_id: 'ITM-000132',
    name: 'ハンドソープ 詰め替え用',
    derived_stock: 155,
    avg_daily_consumption: 7.2,
    days_of_cover: 21.5,
    lead_time_days: 14,
    safety_stock: 60,
    lot_size: 100,
    target_cover_days: 28,
    need_qty: 106.6,
    reorder_qty_suggested: 200,
    risk_level: 'yellow',
    default_unit_cost: 290,
    listings: [
      {
        listing_id: 'metro|01234|SKU-I1',
        store_id: 'metro',
        rakuten_item_no: '01234',
        rakuten_sku: 'SKU-I1',
        title: 'ハンドソープ 詰め替え用 450ml',
        stock_qty: 95,
        last_month_sales: 142,
        this_month_sales: 92,
        r_hat: 5.0,
        bom_qty: 1,
        contribution_stock: 95,
        contribution_consumption: 5.0,
      },
      {
        listing_id: 'metro|01234|SKU-I2',
        store_id: 'metro',
        rakuten_item_no: '01234',
        rakuten_sku: 'SKU-I2',
        title: 'ハンドソープ 詰め替え用 3本セット',
        stock_qty: 20,
        last_month_sales: 28,
        this_month_sales: 18,
        r_hat: 0.73,
        bom_qty: 3,
        contribution_stock: 60,
        contribution_consumption: 2.2,
      },
    ],
  },
];

export const mockMirrorMismatches: MirrorMismatch[] = [
  {
    internal_id: 'ITM-000123',
    name: 'デッキブラシ替えスポンジ',
    metro_stock_qty: 10,
    windy_stock_qty: 8,
    diff: 2,
  },
  {
    internal_id: 'ITM-000456',
    name: 'ハンドソープ 詰め替え用 450ml',
    metro_stock_qty: 15,
    windy_stock_qty: 18,
    diff: -3,
  },
];

export const mockPOHeaders: POHeader[] = [
  {
    po_id: 'PO-20260120-001',
    created_at: '2026-01-20T09:00:00+09:00',
    status: 'sent',
    supplier: 'サプライヤーA',
    note: '通常発注',
  },
  {
    po_id: 'PO-20260119-002',
    created_at: '2026-01-19T14:30:00+09:00',
    status: 'draft',
    supplier: 'サプライヤーB',
    note: '在庫補充',
  },
  {
    po_id: 'PO-20260118-001',
    created_at: '2026-01-18T10:15:00+09:00',
    status: 'sent',
    supplier: 'サプライヤーA',
    note: '',
  },
];

export const mockPOLines: Record<string, POLine[]> = {
  'PO-20260120-001': [
    {
      po_id: 'PO-20260120-001',
      line_no: 1,
      internal_id: 'ITM-000123',
      qty: 100,
      unit_cost: 320,
      basis_need_qty: 74.6,
      basis_days_of_cover: 14.1,
    },
    {
      po_id: 'PO-20260120-001',
      line_no: 2,
      internal_id: 'ITM-000127',
      qty: 100,
      unit_cost: 420,
      basis_need_qty: 52.2,
      basis_days_of_cover: 12.5,
    },
  ],
  'PO-20260119-002': [
    {
      po_id: 'PO-20260119-002',
      line_no: 1,
      internal_id: 'ITM-000125',
      qty: 50,
      unit_cost: 180,
      basis_need_qty: 31,
      basis_days_of_cover: 21.1,
    },
  ],
  'PO-20260118-001': [
    {
      po_id: 'PO-20260118-001',
      line_no: 1,
      internal_id: 'ITM-000126',
      qty: 100,
      unit_cost: 240,
    },
  ],
};
